article_gen/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('process-request/', views.ajax_process_request, name='send_request'),
]

core/models.py
from django.db import models


# Create your models here.


class Phrase(models.Model):
    CATEGORY = (
        ('Technical Article', 'Technical Article'),
        ('Documentation', 'Documentation'),
        ('Proposals', 'Proposals'),
        ('White Papers', 'White Papers'),
        ('Instruction Manuals', 'Instruction Manuals'),
        ('Essay', 'Essay'),
        ('Medical Technical Writing', 'Medical Technical Writing')
    )
    word = models.CharField(max_length=100)
    category = models.CharField(max_length=150, default="Technical Article", choices=CATEGORY)

    def __str__(self):
        return f"word - {self.word}: {self.category}"

    class Meta:
        ordering = ('-id',)


class ArticleTopic(models.Model):
    phrase = models.ForeignKey(Phrase, on_delete=models.CASCADE, related_name='topics')
    title = models.TextField(max_length=150)

    def __str__(self):
        return self.phrase.word + ': ' + self.title

    class Meta:
        ordering = ('-id',)


class Counter(models.Model):
    count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.count)

    class Meta:
        ordering = ('-id',)

core/forms.py
from django import forms
from .models import Phrase

TOPIC_COUNTER = [(i, str(i)) for i in range(1, 11)]


class PhraseForm(forms.ModelForm):
    count = forms.TypedChoiceField(choices=TOPIC_COUNTER, coerce=int)

    class Meta:
        model = Phrase
        fields = ('category',)
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control form-control-lg'})
        }
        labels = {'category': ''}

core/views.py
import json

import requests
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import render
from decouple import config
from .models import Phrase, ArticleTopic, Counter
from .forms import PhraseForm


def home(request):
    # counter, _ = Counter.objects.get_or_create()
    form = PhraseForm()

    return render(request, 'core/home.html', {'form': form})


def ajax_process_request(request):
    try:
        phrase = request.POST.get("topic", None).lower()
        category = request.POST.get("category", None)
        count = request.POST.get("count", None) or 5
        count = int(count) if int(count) < 10 else 5
        out = []
        phrase, _ = Phrase.objects.get_or_create(word=phrase)
        response = send_api_request(phrase, category, count)
        current_count, _ = Counter.objects.get_or_create()
        current_count.count += 1
        current_count.save()
        for title in response:
            if title != "" and title != "\n":
                title = ' '.join(title.rsplit()[1:])
                ArticleTopic.objects.create(phrase=phrase, title=title)
                out.append(title)
        return JsonResponse({"data": out, 'exist': False})
    except Exception as e:
        return JsonResponse({'error': str(e)})


# def ajax_process_request(request):
#     out = []
#     phrase = request.GET.get("topic", None).lower()
#
#     response = send_api_request(phrase)
#     current_count, _ = Counter.objects.get_or_create()
#     current_count.count += 1
#     current_count.save()
#     for title in response:
#         if title != "" and title != "\n":
#             title = ' '.join(title.rsplit()[1:])
#             out.append(title)
#     return JsonResponse({"data": out, 'exist': False, 'counter': current_count.count})


def send_api_request(keyword: str, category: str, count: int):
    api_key = settings.OPEN_API_KEY
    url = "https://api.openai.com/v1/completions"
    headers = {"Content-Type": "application/json",
               "Authorization": f"Bearer {api_key}"}
    data = {
        "model": "text-davinci-003",
        "prompt": f"write out {count} unique, creative and engaging topics for a {category} on {keyword}.",
        "temperature": 0.6,
        "max_tokens": 100,
        "top_p": 1,
        "frequency_penalty": 0,
        "presence_penalty": 0
    }
    d = json.dumps(data)
    response = requests.post(url, headers=headers, data=d)
    output = response.json()
    if not output.get('error'):
        text = output.get('choices')[0].get('text')
        text = text.split('\n')
    else:
        text = ["A server Error due to request overload, Try again..."]
    return text


def check_keyword_exists(keyword: str):
    try:
        phrase = Phrase.objects.get(word=keyword)
        output = [x.title for x in phrase.topics.all()]
        return True, output
    except Phrase.DoesNotExist:
        return False, []

core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sofia+Sans:wght@700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    {#    ajax#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"
            integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <title>Technical Article Generator</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
</head>
<body class="text-center">
    {% include 'core/header.html' %}

<div class="row">
<main class="container-fluid mt-5">
    {% block content %}

    {% endblock %}
</main>
</div>

<!-- Bootstrap core JavaScript
   ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"
        integrity="sha512-efUTj3HdSPwWJ9gjfGR71X9cvsrthIA78/Fvd/IN+fttQVy7XWkOAXb295j8B3cmm/kFKVxjiNYzKw9IQJHIuQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

{#<script>window.jQuery || document.write('<script src="{% static 'js/jquery-slim.min.js' %}"><\/script>')</script>#}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
</script>
</body>
</html>

core/templates/core/header.html
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            <div class="inner">
                <a href="/"><h3 class="masthead-brand"><span>Technical Topics Generator</span></h3></a>
                <nav class="nav nav-masthead justify-content-center">
                    <a class="nav-link active" href="#">Home</a>
                    <a class="nav-link" href="javascript:scrollTo('about-me')">About Me</a>
                    <a class="nav-link" href="javascript:scrollTo('contact')">Contact</a>
                </nav>
            </div>
        </header>

core/templates/core/home.html
{% extends "core/base.html" %}

{% block content %}
    <h1 class="cover-heading">Writing Technical Article is already challenging, finding topics shouldn't
        pose an additional challenge</h1>
    <p class="lead"></p>
    <hr style="color:white;">
    {#            <div id="counter">#}
    {#                <h1 id="counter" class="cover-heading">We have generated <span>{{ counter }}</span> TItle{{ counter | pluralize }} so far</h1>#}
    {#            </div>#}
    <form method="POST" id="topic-form" class="mb-4">
    {% csrf_token %}
        <div class="form-group pt-4">
            <input type="text" name='input_topic' class="form-control form-control-lg" id="topic"
                   placeholder="Enter a Word/Phrase e.g Django Models..." autocomplete="off">
        </div>
        <div class="row">
            <div class="col-md-8">
                {{ form.category }}

            </div>
            <div class="col-md-4">
                <input name='title_count' class="form-control form-control-lg" type="number" min="1" max="10"
                       placeholder="7" id="id_count">
            </div>
        </div>
    </form>
    <p class="lead">
        <button type="submit" class="btn btn-lg btn-secondary" id="generate-button"
                onclick="sendRequest();">Generate Topics
        </button>
        <button class="btn btn-lg btn-success" onclick="reset();" id="reset-button">Reset</button>
    </p>
    <div id="topic-container">
        <h3 class="mt-2 mb-1 cover-heading">Generated Topics</h3>
        <p id="exists"></p>
        <ul class="list-group list-group-flush mb-3" id="topic-list">

        </ul>
    </div>
    <div class="pt-5">
        <h1 id="about-me" class="cover-heading">About</h1>
        <p>Topics Generator is an online tool designed to help you generate creative, interesting and engaging topics
            for
            your content. Our intuitive user interface and powerful algorithms make it easy to quickly generate ideas
            for
            articles, blog posts, essays, and more. whether you’re a writer, editor, or content creator, Topics
            Generator is
            the perfect tool to help you come up with new ideas and keep your content fresh.</p>
    </div>

    <footer class="mastfoot mt-auto">
        <div class="inner" id="contact">
            <p>Made with Love <a href="https://www.linkedin.com/in/lawal-afeez/">by Lawal Afeez</a> |
                <a href="https://github.com/afeez1131">@afeez1131</a>.</p>
        </div>
    </footer>
    <script type="text/javascript">
        $(document).ready(
            documentReady()
        )

        function documentReady() {
            let topic = $('#topic');
            topic.focus()

            $('#topic-container').hide()
            if ($('#topic-container ul').html().trim().length === 0) {
                $('#reset-button').prop('disabled', true);
            }
        }

        let inputForm = document.getElementById('topic');
        inputForm.addEventListener('input', function () {
            let topic = $('#topic');
            if (topic.val() === "" || topic.val().length === 0) {
                console.log('emtpy')
                topic.addClass('is-invalid')
            } else {
                topic.removeClass('is-invalid').addClass('is-valid');
            }
        })


        function reset() {
            $('#topic-container ul').html('');
            $('#topic-container').hide();
            $('#reset-button').prop('disabled', true);
        }

        function scrollTo(id) {
            document.querySelector('#' + id).scrollIntoView({behavior: 'smooth'});
        }

        $('#topic, #id_count, #id_category').keyup(function (e) {
            if (e.which === 13) {
                /* we only need the enter key press,
                * whenever any other key is pressed, do nothing
                * if enter is pressed, proceed. */
                if ($('#topic').val().trim().length !== 0) {
                    sendRequest();
                } else {
                    $.notify('Input cannot be empty', 'error');
                }
            }
        })

        /*function submitForm() {
            $('#topic-form').submit(function (e) {
                e.preventDefault();
                console.log('form submitted');
                if ($('#topic').val().trim().length !== 0) {
                    sendRequest();
                } else {
                    $.notify('Input cannot be empty', 'error');
                }

            })
        }*/


        function sendRequest() {
            if ($('#topic').val().trim().length !== 0) {
                $('#generate-button').html(`Generating <i class="fas fa-spinner fa-spin"></i>`)
                $.ajax({
                    url: "{% url 'send_request' %}",
                    type: "POST",
                    data: {
                        'topic': $('#topic').val(),
                        'count': $('#id_count').val(),
                        'category': $('#id_category option:selected').val(),
                        'csrfmiddlewaretoken': getCookie('csrftoken')
                    },
                    success: function (data) {
                        if (data.data) {
                            let objectData = data.data;
                            /*let exists = data.exist
                            if (exists === true) {
                                $('#exists').html(`We have some previously generated titles related to "${topic}"<br>
                                                Or you can generate a new one by clicking here`);
                            } else {
                                $('#exists').text('');
                            }*/
                            let topic = $('#topic').val();
                            $('#reset-button').prop('disabled', false);
                            $('#topic').val('')   // clear the value of the input
                            $('#id_count').val('')
                            $('#id_category option:first').prop('selected', true);
                            let arrayLength = objectData.length;
                            let output = ''
                            $('#generate-button').html("Generate Topics")
                            for (let i = 0; i < arrayLength; i++) {
                                $('#topic-list').val('')
                                output += `<li class="list-group-item d-flex justify-content-between align-items-center" id='topic-${i}'>${i + 1}. <span>${objectData[i]}</span>
                                <button class="badge badge-secondary" onclick="copyTitle('${i}');">Copy <i class="fas fa-copy"></i></button>
                                </li>`
                            }
                            $('#counter span').text(data.counter)
                            $('#topic-list').html(output);
                            $.notify('success', 'success');
                            $('#topic-container h3').html(`Generated Titles for <b>${topic.toUpperCase()}</b>`)
                            $('#topic-container').show()
                        } else if (data.error) {
                            $.notify(data.error, 'error');
                        }
                    },
                    error: function () {
                        console.log('error occured')
                        $.notify('Error occured', 'error');
                    },

                })
            } else {
                $.notify('Input cannot be empty', 'error');
            }
        }

        function copyTitle(id) {
            let tid = $(`#topic-${id} span`).text().trim();

            let temp = document.createElement('input');
            temp.value = tid;
            document.body.appendChild(temp);
            temp.select()

            document.execCommand("copy");
            document.body.removeChild(temp);
            $.notify(`${tid} copied.`, 'success');

        }



    </script>
{% endblock %}